[package]
name = "eldenr"
version = "0.0.1"
edition = "2021"

[dependencies]
akaze = "*"
anyhow = "*"
arrsac = "*"
bitarray ="*"
chrono = "*"
cv = "0.6.0"
cv-core = "*"
enigo = "0.0.14"
gamepad = "*"
gilrs = "0.8.2"
image = "0.23.*"
imageproc = "0.22.0"
open = "2.*"
opencv = "0.62.0"
prettytable-rs = "^0.8"
pscontroller-rs= "0.6.0"
rand = "*"
repng = "*"
scrap = "*"
tempfile = "3.*"
winput = "*"
